name: nextcloud
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.0.0
  collection: ^1.0.0
  crypto: ^3.0.0
  crypton: ^2.0.0
  dynamite_runtime:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/dynamite/dynamite_runtime
  intl: ^0.18.0
  json_annotation: ^4.8.1
  meta: ^1.0.0
  universal_io: ^2.0.0
  uri: ^1.0.0
  version: ^3.0.0
  xml: ^6.0.0
  xml_annotation: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.7
  built_value_generator: ^8.8.1
  coverage: ^1.7.2
  dynamite:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/dynamite/dynamite
  json_serializable: ^6.7.1
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  nextcloud_test:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/nextcloud_test
  path: ^1.9.0
  process_run: ^0.13.3
  test: ^1.24.9
  test_api: ^0.7.0
  xml_serializable: ^2.4.0
