name: nextcloud
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.4.4
  cookie_jar: ^3.0.1
  crypto: ^3.0.2
  crypton: ^2.0.5
  intl: ^0.17.0
  version: ^3.0.2
  xml: ^6.1.0

dev_dependencies:
  build_runner: ^2.2.1
  built_value_generator:
    git:
      url: https://github.com/leptopoda/built_value.dart
      path: built_value_generator
      ref: d4a7937f5f968db1dfa2c5ea60ca9ca1f49f9bb5
  coverage: ^1.6.1
  dynamite:
    path: ../dynamite
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d
  process_run: ^0.12.5+2
  test: ^1.16.0
