name: nextcloud
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  crypton: ^2.0.5
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  meta: ^1.7.0
  path: ^1.8.1
  version: ^3.0.2
  xml: ^6.1.0

dev_dependencies:
  build_runner: ^2.2.1
  coverage: ^1.6.1
  dynamite:
    path: ../dynamite
  json_serializable: ^6.3.2
  nextcloud_push_proxy:
    path: ../nextcloud_push_proxy
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: f29382f
  process_run: ^0.12.3+1
  test: ^1.16.0
