name: nextcloud
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.5.0
  cookie_jar: ^4.0.2
  crypto: ^3.0.3
  crypton: ^2.0.5
  dynamite_runtime:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/dynamite/dynamite_runtime
  intl: ^0.18.0
  universal_io: ^2.2.0
  version: ^3.0.2
  xml: ^6.3.0
  xml_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.2
  built_value_generator: ^8.5.0
  coverage: ^1.6.3
  dynamite:
    path: ../dynamite/dynamite
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d
  process_run: ^0.13.0
  test: ^1.24.2
  xml_serializable: ^2.2.2

dependency_overrides:
  dynamite_runtime:
    path: ../dynamite/dynamite_runtime
