targets:
  $default:
    builders:
      built_value_generator|built_value:
        enabled: true
      dynamite:
        options:
          analyzer_ignores:
            - camel_case_types
            - camel_case_extensions
            - discarded_futures
            - public_member_api_docs
            - unreachable_switch_case
            - unused_element
            - no_leading_underscores_for_local_identifiers
            - non_constant_identifier_names
            - library_private_types_in_public_api
          overrides:
            lib/documentation.openapi.json:
              analyzer_ignores:
                - camel_case_types
                - camel_case_extensions
                - discarded_futures
                - unreachable_switch_case
                - unused_element
                - no_leading_underscores_for_local_identifiers
                - non_constant_identifier_names
                - library_private_types_in_public_api
