name: cookbook_app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: ^3.22.0

dependencies:
  built_collection: ^5.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.0.0
  intl: ^0.19.0
  logging: ^1.0.0
  meta: ^1.0.0
  neon_framework:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework
  nextcloud: ^6.1.0

dev_dependencies:
  build_runner: ^2.4.11
  built_value_test: ^8.9.2
  custom_lint: ^0.6.7
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0
  mocktail: ^1.0.4
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  vector_graphics_compiler: ^1.1.11+1

flutter:
  uses-material-design: true
  assets:
    - assets/
