name: neon_talk
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.9.0
  collection: ^1.0.0
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.12
  flutter_localizations:
    sdk: flutter
  flutter_material_design_icons: ^1.0.0
  flutter_parsed_text: ^2.1.0
  flutter_webrtc: ^0.9.48+hotfix.1
  go_router: ^13.0.0
  intersperse: ^2.0.0
  logging: ^1.0.0
  meta: ^1.0.0
  neon_framework:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework
  nextcloud: ^5.0.2
  rxdart: ^0.27.0
  vector_graphics: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  http: ^1.2.1
  mocktail: ^1.0.3
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  vector_graphics_compiler: ^1.1.11+1

flutter:
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  package_info_plus:
    git:
      url: https://github.com/fluttercommunity/plus_plugins
      path: packages/package_info_plus/package_info_plus
      ref: baa336fe79c29411542fc343d332846bcd7752c1
