name: nextcloud_test
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  built_collection: ^5.0.0
  cookie_store:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/cookie_store
  glob: ^2.1.2
  http: ^1.2.0
  interceptor_http_client:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/interceptor_http_client
  meta: ^1.0.0
  nextcloud: ^7.0.0
  nextcloud_test_api:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/nextcloud/packages/nextcloud_test_api
  path: ^1.9.0
  test: ^1.24.0
  test_api: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.11
  built_value_generator: ^8.9.2
  built_value_test: ^8.9.2
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
