name: nextcloud_test
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  built_collection: ^5.1.1
  cookie_store:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/cookie_store
  glob: ^2.1.2
  http: ^1.2.0
  interceptor_http_client:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/interceptor_http_client
  meta: ^1.0.0
  nextcloud: ^7.0.0
  path: ^1.9.0
  process_run: ^1.0.0+1
  test: ^1.24.0
  test_api: ^0.7.0
  timezone: ^0.9.4
  universal_io: ^2.0.0
  version: ^3.0.0

dev_dependencies:
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
