name: cookbook_recipe_repository
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.9.2
  equatable: ^2.0.0
  nextcloud: ^6.1.0
  timezone: ^0.9.4

dev_dependencies:
  build_runner: ^2.4.11
  built_value_generator: ^8.9.2
  built_value_test: ^8.9.2
  mocktail: ^1.0.4
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  test: ^1.25.0
