name: sort_box
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dev_dependencies:
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  test: ^1.25.0
