name: dynamite_runtime
description: Helper package for use with dynamite.
version: 1.0.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  built_value: ^8.6.2
  cookie_jar: ^4.0.8
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  built_collection: ^5.1.1
  built_value_generator: ^8.6.3
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  test: ^1.24.6
