name: dynamite_runtime
description: Helper package for use with dynamite.
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.0.1
  collection: ^1.0.0
  cookie_jar: ^4.0.7
  meta: ^1.0.0
  universal_io: ^2.0.0
  xml: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.7
  built_value_generator: ^8.8.1
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  test: ^1.25.0
