name: files_app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.5.0
  flutter: ^3.22.0

dependencies:
  built_collection: ^5.0.0
  collection: ^1.0.0
  dynamite_runtime: ^0.5.0
  file_picker: ^8.0.0+1
  files_icons:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework/packages/files_icons
  filesize: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_material_design_icons: ^1.0.0
  go_router: ^14.0.0
  image_picker: ^1.0.0
  intl: ^0.19.0
  logging: ^1.0.0
  meta: ^1.0.0
  neon_framework:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework
  nextcloud: ^7.0.0
  open_filex: ^4.4.0
  path: ^1.0.0
  path_provider: ^2.0.0
  queue: ^3.0.0
  rxdart: ^0.27.0
  share_plus: ^10.0.0
  timezone: ^0.9.4
  universal_io: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  go_router_builder: ^2.7.1
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  vector_graphics_compiler: ^1.1.11+1

flutter:
  uses-material-design: true
  assets:
    - assets/
