name: Conventional commits
on:
  pull_request:

jobs:
  conventional-commits:
    name: Conventional commits
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0

      - name: Install dart
        uses: dart-lang/setup-dart@f0ead981b4d9a35b37f30d36160575d60931ec30 # v1
      - name: Install commitlint_cli
        run: dart pub get

      - name: Lint conventional commits
        run: dart run commitlint_cli --from=${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to=${{ github.event.pull_request.head.sha }}
