name: Dart CI
on:
  pull_request:

concurrency:
  group: dart-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dart-ci:
    name: Dart CI
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - name: Login to GHCR
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # v3
      - name: Build test Docker image
        run: ./tool/build-dev-container.sh

      - name: Install dart
        uses: dart-lang/setup-dart@fedb1266e91cf51be2fdb382869461a434b920a3 # v1
      - name: Setup
        run: |
          ./tool/setup.sh
          # Remove any changes from the automatic formatting
          git checkout .

      - name: Check formatting
        run: melos run format:check
      - name: Lint code
        run: melos run analyze
      - name: Run tests
        run: |
          mapfile -t packages < <(melos list --parsable --diff=${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }}..${{ github.event.pull_request.head.sha }} --include-dependents | xargs -r -n1 basename)
          if [ -z "$packages" ]; then exit 0; fi
          packages_glob="$(printf ",%s" "${packages[@]}")"
          packages_glob="${packages_glob:1}"
          MELOS_PACKAGES="$packages_glob" melos test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@c16abc29c95fcf9174b58eb7e1abf4c866893bc8 # v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 
          codecov_yml_path: ./github/codecov.yaml
          exclude: .fvm
          fail_ci_if_error: true
          slug: nextcloud/neon
