name: Lint
on:
  pull_request:

concurrency:
  group: lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Find untested Neon APIs
        run: ./tool/find-untested-neon-apis.sh

      - name: Find relative markdown links
        run: ./tool/find-relative-markdown-links.sh
