name: Lint
on:
  pull_request:

concurrency:
  group: lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Find untested Neon APIs
        run: ./tool/find-untested-neon-apis.sh

      - name: Find dart:io usage
        run: ./tool/find-dart-io-usage.sh

      - name: Find relative markdown links
        run: ./tool/find-relative-markdown-links.sh
