name: 'Update test presets'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - name: Install dart
        uses: dart-lang/setup-dart@ca7e6fee45ffbd82b555a7ebfc236d2c86439f5b # v1
      - name: Setup
        run: ./tool/setup.sh

      - name: Update presets
        run: ./tool/generate-nextcloud-test-presets.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5
        with:
          commit-message: "chore(nextcloud_test): Update presets"
          signoff: true
          branch: chore/nextcloud_test/update-presets
          delete-branch: true
          title: "chore(nextcloud_test): Update presets"
          body: ""
