name: 'Update test presets'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0
      - name: Install dart
        uses: dart-lang/setup-dart@f0ead981b4d9a35b37f30d36160575d60931ec30 # v1
      - name: Setup
        run: ./tool/setup.sh

      - name: Update presets
        run: ./tool/generate-nextcloud-test-presets.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6
        with:
          commit-message: "chore(nextcloud_test): Update presets"
          signoff: true
          branch: chore/nextcloud_test/update-presets
          delete-branch: true
          title: "chore(nextcloud_test): Update presets"
          body: ""
